Migrate to politeia tlog API
planetdecred/pdanalytics pull request #43
Opened 2021-09-08 09:54 UTC by crux25

This PR implements the changes needed to migrate to the new Politeia tlog API. 
Specifically this PR:

1. Drops the use of go-piparser module.
2. Fetch chartdata from politeia API and save it with proposal object in stormdb.
3. Drop the use of Axios in proposal module and instead use a more lightweight helper function.
4. Clean up codes.

2021-09-19 04:11 UTC, Ekeh requested changes
Kindly, check the display of the proposal on mobile and adjust the margin from the top.

![proposal_page](https://user-images.githubusercontent.com/17119508/133915158-ea18cc6e-4829-4aca-861f-f18fb021336a.jpg).

2021-09-22 14:00 UTC, crux25 commented
> Kindly, check the display of the proposal on mobile and adjust the margin from the top.
> 
> ![proposal_page](https://user-images.githubusercontent.com/17119508/133915158-ea18cc6e-4829-4aca-861f-f18fb021336a.jpg).
This is fixed now.

2021-09-22 17:22 UTC, Ekeh approved these changes
This PR has been reviewed and all looks good.

2021-10-22 01:20 UTC, crux25 commented on gov/politeia/handler.go
> +		proposalToken := chi.URLParam(r, "proposaltoke")
I have fixed it in c5e5bd59cbfbb8231071ec71470a805c5bf84c51

2021-11-03 11:51 UTC, merged